service: mtglm-players

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  memorySize: 128
  environment:
    ALLOWED_ORIGIN: ${env:ALLOWED_ORIGIN}
    TABLE_NAME: ${self:provider.stage}-mtglm-players
    USER_POOL_ID:
      Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolId

package:
  include:
    - ../build/**
    - ../node_modules/**

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-aws-documentation

resources:
  Resources:
    PlayersApiGatewayAuthorizer: ${file(partials/apiGatewayAuthorizer.yml)}
    PlayersTable: ${file(partials/dynamo.yml)}
  Outputs:
    playerTableArn: ${file(partials/outputs/TableArn.yml)}
    playerTableName: ${file(partials/outputs/TableName.yml)}

custom:
  documentation: ${file(partials/documentation.yml)}
  userPoolArn: 
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolArn
  userPoolName: 
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolName

functions:
  Get: ${file(partials/functions/get.yml)}
  Update: ${file(partials/functions/update.yml)}
  Create: ${file(partials/functions/create.yml)}
  Delete: ${file(partials/functions/delete.yml)}
