service: mtglm-players

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  memorySize: 128
  environment:
    ALLOWED_ORIGIN: ${env:ALLOWED_ORIGIN}

package:
  include:
    - ../build/**
    - ../node_modules/**

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function
  - serverless-aws-documentation

resources:
  Resources:
    PlayersApiGatewayAuthorizer: ${file(partials/apiGatewayAuthorizer.yml)}

custom:
  documentation: ${file(partials/documentation.yml)}
  userPoolArn: 
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolArn
  userPoolName: 
    Fn::ImportValue: ${self:provider.stage}-mtglm-UserPoolName

functions:
  Get: ${file(partials/functions/get.yml)}
  Query: ${file(partials/functions/query.yml)}
